version: '3.8'

services:

  web:
    build:
      context: .
    image: schetininl/api_yamdb
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
