# Generated by Django 3.0.5 on 2020-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reviews&comments', '0002_auto_20200505_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
