# Generated by Django 3.0.5 on 2020-05-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_reviews&comments', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.DecimalField(choices=[(1.0, '1'), (2.0, '2'), (3.0, '3'), (4.0, '4'), (5.0, '5'), (6.0, '6'), (7.0, '7'), (8.0, '8'), (9.0, '9'), (10.0, '10')], decimal_places=2, max_digits=5),
        ),
    ]
