# Generated by Django 3.0.5 on 2020-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_genre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
